Handle `snapctl stop` failing

diff --git a/bin/run-daemon b/bin/run-daemon
--- a/bin/run-daemon
+++ b/bin/run-daemon
@@ -4,5 +4,11 @@ set -x
 
 if [ "$(snapctl get daemon)" = "true" ]
 then exec "$@"
-else snapctl stop $SNAP_NAME.daemon
+else
+  # It is unlikely, but possible "snapctl stop ..." to fail
+  # temporarily (e.g. during install/refresh).
+  # Handle failure by ignoring it: it will work next retry.
+  # NB We don't move the logic to a `configure` hook, as that
+  # might conflict with any downstream snaps.
+  snapctl stop $SNAP_NAME.daemon || true
 fi
