Check that inotifywait is snapped

diff --git a/bin/wayland-launch b/bin/wayland-launch
--- a/bin/wayland-launch
+++ b/bin/wayland-launch
@@ -8,6 +8,14 @@ for PLUG in %PLUGS%; do
   fi
 done
 
+if ! command -v inotifywait > /dev/null
+then
+    echo "ERROR: inotifywait could not be found, mir-kiosk-snap-launch expects:"
+    echo " . . :     stage-packages:"
+    echo " . . :        - inotify-tools"
+    exit 1
+fi
+
 wait_for()
 {
   until
